"""
	Takes in IC's generated by music, and combines them so that
	they can be used in enzoBWG
"""


import h5py
import numpy as np
dim = 128
rank = np.array([3])
size = dim*dim*dim
dims = np.array([dim,dim,dim])
topGridStart = np.array([0,0,0])
tge = np.array([-100000, -100000, -100000])
tgd = np.array([-99999, -99999, -99999])
test = h5py.File('../64_amr/ParticlePositions','r')
print('known', test)
for k in test: print(k)
ta = test['ParticlePositions'].attrs
for a in ta:
	print(ta[a])
print(test['ParticlePositions'][0])
test.close()
test = h5py.File('../64_amr/GridDensity','r')
print('known',test)
for k in test: print(k)
ta = test['GridDensity'].attrs
for a in ta:
	print('%s: '%a, ta[a])
test.close()
fx = h5py.File('ic.enzo/GridVelocities_x','r')
fy = h5py.File('ic.enzo/GridVelocities_y','r')
fz = h5py.File('ic.enzo/GridVelocities_z','r')
print('in fz')
for a in list(fz['GridVelocities_z'].attrs):#
	print(a,fz['GridVelocities_z'].attrs[a])
out = np.zeros((3,dim,dim,dim))
out[0] = fx['GridVelocities_x'][0]
out[1] = fy['GridVelocities_y'][0]
out[2] = fz['GridVelocities_z'][0]
fout = h5py.File('GridVelocities','w')
fout.create_dataset('GridVelocities',data=out, dtype='>f8')
fout['GridVelocities'].attrs['Component_Rank'] = [3]#rank
fout['GridVelocities'].attrs['Component_Size'] = [fx['GridVelocities_x'].attrs['Component_Size']]
fout['GridVelocities'].attrs['Rank'] = [fx['GridVelocities_x'].attrs['Rank']]
fout['GridVelocities'].attrs['Dimensions'] = fx['GridVelocities_x'].attrs['Dimensions']
fout['GridVelocities'].attrs['TopGridStart'] = fx['GridVelocities_x'].attrs['TopGridStart']
fout['GridVelocities'].attrs['TopGridEnd'] = tge #fx['GridVelocities_x'].attrs['TopGridEnd']
fout['GridVelocities'].attrs['TopGridDims'] = tgd #fx['GridVelocities_x'].attrs['TopGridDims']
fout.close()
fwrite = h5py.File('GridVelocities','r')
print(fwrite)
for k in fwrite: print(k)
print(list(fwrite['GridVelocities'].attrs))
for a in list(fwrite['GridVelocities'].attrs):#
	print(a,fwrite['GridVelocities'].attrs[a])
fwrite.close()
test = h5py.File('./ic.enzo/GridDensity','r+')
print(test)
for k in test: print(k)
ta = test['GridDensity'].attrs
for a in ta:
	print(a,ta[a])
fout = h5py.File('GridDensity','w')
denOut = np.array(test['GridDensity'][0])
fout.create_dataset('GridDensity', data=denOut, dtype = '>f8')
fout["GridDensity"].attrs['Component_Size'] = [fx['GridVelocities_x'].attrs['Component_Size']]
fout["GridDensity"].attrs['Component_Rank'] = [1]
fout['GridDensity'].attrs['Rank'] = [3]
fout['GridDensity'].attrs['Dimensions'] = test['GridDensity'].attrs['Dimensions']
fout['GridDensity'].attrs['TopGridDims'] = tgd
fout['GridDensity'].attrs['TopGridEnd'] = tge
fout['GridDensity'].attrs['TopGridStart'] = test['GridDensity'].attrs['TopGridStart']
fout.close()
test.close()
fx = h5py.File('ic.enzo/ParticleDisplacements_x','r')
fy = h5py.File('ic.enzo/ParticleDisplacements_y','r')
fz = h5py.File('ic.enzo/ParticleDisplacements_z','r')

out[0] = fx['ParticleDisplacements_x'][0]
out[1] = fy['ParticleDisplacements_y'][0]
out[2] = fz['ParticleDisplacements_z'][0]
dx = 1.0/dim
for a in range(3):
    for i in range(dim):
        for j in range(dim):
            for k in range(dim):
                out[a][:][j][k] = out[a][:][j][k] + dx * i
                out[a][i][:][k] = out[a][i][:][k] + dx * j
                out[a][i][j][:] = out[a][i][j][:] + dx * k
			
#print(out[0])
fout = h5py.File('ParticlePositions','w')
#fwrite = fout.create_group('ParticlePositions')
fout.create_dataset('ParticlePositions', data = out, dtype='>f8')
fout['ParticlePositions'].attrs['Component_Rank'] = rank
fout['ParticlePositions'].attrs['Component_Size'] = [size]
fout['ParticlePositions'].attrs['Rank'] = rank
fout['ParticlePositions'].attrs['Dimensions'] = dims
fout['ParticlePositions'].attrs['TopGridStart'] = topGridStart
fout['ParticlePositions'].attrs['TopGridEnd'] = tge #topGridEnd
fout['ParticlePositions'].attrs['TopGridDims'] = tgd #topGridDims
fout.close()

fx = h5py.File('ic.enzo/ParticleVelocities_x','r')
fy = h5py.File('ic.enzo/ParticleVelocities_y','r')
fz = h5py.File('ic.enzo/ParticleVelocities_z','r')

out[0] = fx['ParticleVelocities_x'][0]
out[1] = fy['ParticleVelocities_y'][0]
out[2] = fz['ParticleVelocities_z'][0]

fout = h5py.File('ParticleVelocities','w')
fout.create_dataset('ParticleVelocities', data = out, dtype='>f8')
fout['ParticleVelocities'].attrs['Component_Rank'] = rank
fout['ParticleVelocities'].attrs['Component_Size'] = [size]
fout['ParticleVelocities'].attrs['Rank'] = rank
fout['ParticleVelocities'].attrs['Dimensions'] = dims
fout['ParticleVelocities'].attrs['TopGridStart'] = topGridStart
fout['ParticleVelocities'].attrs['TopGridEnd'] = tge #topGridEnd
fout['ParticleVelocities'].attrs['TopGridDims'] = tgd #topGridDims

#fwrite = fout.create_group('ParticleVelocities')
fout.close()


